// Pure generators for the committed CSS files (run `pnpm --filter @mc/ui generate`). Kept pure so the
// unit test can regenerate in memory and fail when a committed file is stale.
import { COLORS, LAYOUT, LOCALE_TYPE, RADII, SHADOWS, TYPE_SCALE, type TypeStyle } from './tokens.ts';

const HEADER = '/* GENERATED by packages/ui/scripts/generate.ts from src/tokens — do not edit by hand. */\n';
const rem = (px: number) => `${String(px / 16)}rem`;

/**
 * `tokens.css`: Tailwind v4 theme with the default palette, fonts, radii, shadows, type sizes, tracking,
 * leading, easings and animations **removed**, so only design tokens can be used (06 §2, PHASE_00 T0.6).
 * `static` emits every variable (components and SVGs may read `var(--color-*)` directly).
 */
export function tokensCss(): string {
  const colors = Object.entries(COLORS).map(([name, value]) => `  --color-${name}: ${value};`);
  const radii = Object.entries(RADII).map(([name, value]) => `  --radius-${name}: ${value};`);
  const shadows = Object.entries(SHADOWS).map(([name, value]) => `  --shadow-${name}: ${value};`);
  return `${HEADER}
@theme static {
  --color-*: initial;
  --font-*: initial;
  --text-*: initial;
  --tracking-*: initial;
  --leading-*: initial;
  --radius-*: initial;
  --shadow-*: initial;
  --inset-shadow-*: initial;
  --drop-shadow-*: initial;
  --text-shadow-*: initial;
  --ease-*: initial;
  --animate-*: initial;

  /* 4-pt grid (06 §4): p-1 = 4px … p-12 = 48px, h-11 = 44px, h-14 = 56px. */
  --spacing: 0.25rem;

${colors.join('\n')}

${radii.join('\n')}

${shadows.join('\n')}
}

/* Values that change at runtime per locale / app / viewport are referenced, not inlined. */
@theme inline {
  --font-ui: var(--mc-font-ui);
  --font-arabic: var(--mc-font-arabic);
  --spacing-gutter: var(--mc-gutter);
  --container-content: ${rem(LAYOUT.maxContentPx)};
}

:root {
  --mc-gutter: ${rem(LAYOUT.gutterPx)};
}

@media (width < ${String(LAYOUT.narrowBelowPx)}px) {
  :root {
    --mc-gutter: ${rem(LAYOUT.narrowGutterPx)};
  }
}
`;
}

function typeUtility(name: string, style: TypeStyle): string {
  const lines: string[] = [];
  if (style.family === 'arabic') {
    // Arabic religious text keeps its own fixed scale in every locale and app (06 §3, §6 ArabicText).
    lines.push(
      `  font-family: var(--font-arabic);`,
      `  font-size: ${rem(style.size)};`,
      `  line-height: ${rem(style.lineHeight)};`,
      `  font-weight: ${String(style.weight)};`,
      `  letter-spacing: 0;`,
    );
  } else {
    lines.push(
      `  font-size: calc(${rem(style.size)} + var(--mc-size-bump) + var(--mc-script-size-bump));`,
      `  line-height: max(calc((${rem(style.lineHeight)} + var(--mc-size-bump)) * var(--mc-lh-scale)), calc(var(--mc-lh-min) * 1em));`,
      `  font-weight: ${String(style.weight)};`,
      `  letter-spacing: calc(${String(style.tracking)}em * var(--mc-tracking));`,
    );
  }
  if ('tabular' in style && style.tabular) lines.push(`  font-variant-numeric: tabular-nums;`);
  return `@utility type-${name} {\n${lines.join('\n')}\n}`;
}

/**
 * `type.css`: `type-*` utilities (size + line height + weight + tracking together) and the locale/admin
 * adjustment variables (06 §3). `<html lang>` is set before first paint by `/boot.js` (T0.7).
 */
export function typeCss(): string {
  const utilities = Object.entries(TYPE_SCALE).map(([name, style]) => typeUtility(name, style));
  return `${HEADER}
:root {
  --mc-size-bump: 0rem;
  --mc-script-size-bump: 0rem;
  --mc-lh-scale: 1;
  --mc-lh-min: 0;
  --mc-tracking: 1;
}

/* Admin app: everything +2px (06 §3). */
:root[data-app='admin'] {
  --mc-size-bump: ${rem(LOCALE_TYPE.adminSizeBumpPx)};
}

/* Devanagari / Telugu: taller lines, no negative tracking. */
:root:lang(hi),
:root:lang(te) {
  --mc-lh-scale: ${String(LOCALE_TYPE.indicLineHeightScale)};
  --mc-tracking: 0;
}

/* Nastaliq: +2px, line-height ≥ 1.9, no letter-spacing. */
:root:lang(ur) {
  --mc-script-size-bump: ${rem(LOCALE_TYPE.urduSizeBumpPx)};
  --mc-lh-min: ${String(LOCALE_TYPE.urduMinLineHeight)};
  --mc-tracking: 0;
}

${utilities.join('\n\n')}
`;
}
