// Generates `fonts.css` and `font-fallbacks.css` (Node-only: reads Fontsource CSS and Capsize metrics).
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';

import { createFontStack } from '@capsizecss/core';
import { entireMetricsCollection as metrics } from '@capsizecss/metrics/entireMetricsCollection';
import { LOCALES } from '@mc/i18n/locales';

import { ARABIC_FONT_STACK, FONT_FILES, type FontFile, UI_FONT_STACK } from '../src/fonts/fonts.ts';

const HEADER = '/* GENERATED by packages/ui/scripts/generate.ts from src/fonts — do not edit by hand. */\n';
const require = createRequire(import.meta.url);

/**
 * Finds the `unicode-range` Fontsource declares for a file, so our subset declarations stay identical to
 * upstream when the packages update.
 *
 * @throws when the file is not referenced by the package's CSS (package layout changed).
 */
export function unicodeRangeFor(font: FontFile): string {
  const [scope, name] = font.file.split('/');
  const packageJson = require.resolve(`${String(scope)}/${String(name)}/package.json`);
  const packageDir = packageJson.slice(0, -'package.json'.length);
  const fileName = font.file.slice(font.file.lastIndexOf('/') + 1);
  for (const cssFile of ['index.css', '400.css', '700.css']) {
    let css: string;
    try {
      css = readFileSync(`${packageDir}${cssFile}`, 'utf8');
    } catch {
      continue;
    }
    for (const block of css.split('@font-face').slice(1)) {
      if (!block.includes(`/${fileName})`)) continue;
      const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
      if (range) return range.trim();
    }
  }
  throw new Error(`unicode-range for ${font.file} not found in its Fontsource CSS`);
}

/** `fonts.css`: our subset `@font-face` rules + per-locale font stacks on `<html lang>`. */
export function fontsCss(): string {
  const faces = Object.values(FONT_FILES).map(
    (font) => `@font-face {
  font-family: '${font.family}';
  font-style: normal;
  font-display: swap;
  font-weight: ${font.weight};
  src: url('./node_modules/${font.file}') format('${font.format}');
  unicode-range: ${unicodeRangeFor(font)};
}`,
  );
  const stacks = LOCALES.filter((locale) => locale !== 'en').map(
    (locale) => `:root:lang(${locale}) {\n  --mc-font-ui: ${UI_FONT_STACK[locale]};\n}`,
  );
  return `${HEADER}
${faces.join('\n\n')}

:root {
  --mc-font-ui: ${UI_FONT_STACK.en};
  --mc-font-arabic: ${ARABIC_FONT_STACK};
}

${stacks.join('\n\n')}
`;
}

/**
 * `font-fallbacks.css`: Arial/Roboto faces whose metrics are overridden to match Inter, so swapping to the
 * web font causes no layout shift (09 §6). Arial covers iOS/desktop, Roboto Android. They carry Inter's own
 * Latin `unicode-range`: Arial also has Arabic glyphs, and an unrestricted fallback would draw Urdu text in
 * Arial instead of falling through to Nastaliq.
 */
export function fontFallbacksCss(): string {
  const { fontFaces } = createFontStack([metrics.inter, metrics.arial, metrics.roboto], {
    fontFaceFormat: 'styleString',
    subset: 'latin',
    fontFaceProperties: { unicodeRange: unicodeRangeFor(FONT_FILES.inter) },
  });
  return `${HEADER}\n${fontFaces}\n`;
}
