// Generates `motion.css` (run `pnpm --filter @mc/ui generate`): CSS custom properties for every spring
// (Motion's `spring()` turned into a CSS `linear()` easing) plus the CSS-only motion utilities.
import { spring as springGenerator } from 'motion';

import { css, press, spring, tween } from './tokens.ts';

const HEADER = '/* GENERATED by packages/ui/scripts/generate.ts from src/motion — do not edit by hand. */\n';

/** `500ms linear(…)` for a spring token, as Motion would animate it. */
export function springCss(name: keyof typeof spring): string {
  const { visualDuration, bounce } = spring[name];
  return String(springGenerator(visualDuration, bounce));
}

export function motionCss(): string {
  const springs = (Object.keys(spring) as (keyof typeof spring)[]).map(
    (name) => `  --mc-spring-${name}: ${springCss(name)};`,
  );
  const scales = Object.entries(press).map(([kind, scale]) => `  --mc-press-${kind}: ${String(scale)};`);
  // Browsers without CSS linear() (iOS < 17.2, old WebViews) get the iOS curve at the spring's visual duration.
  const fallbacks = (Object.keys(spring) as (keyof typeof spring)[]).map(
    (name) =>
      `    --mc-spring-${name}: ${String(Math.round(spring[name].visualDuration * 1000))}ms var(--mc-ease-ios);`,
  );
  const ms = (seconds: number) => `${String(Math.round(seconds * 1000))}ms`;
  return `${HEADER}
:root {
${springs.join('\n')}
  --mc-ease-ios: ${css.ios.easing};
  --mc-duration-ios: ${String(css.ios.durationMs)}ms;
  --mc-tween-fade: ${ms(tween.fade.duration)} cubic-bezier(${tween.fade.ease.join(', ')});
  --mc-tween-quick: ${ms(tween.quick.duration)} ease-out;
${scales.join('\n')}
}

@supports not (transition-timing-function: linear(0, 1)) {
  :root {
${fallbacks.join('\n')}
  }
}

/*
 * Press feedback (08 §5.1): the Pressable primitive sets [data-pressed] synchronously on pointerdown; the
 * transform runs on the compositor with the spring.snappy curve. Browsers without CSS linear() keep the
 * cubic-bezier fallback declared first.
 */
@utility pressable {
  transform: scale(1);
  transition: transform var(--mc-duration-ios) var(--mc-ease-ios);
  transition: transform var(--mc-spring-snappy);
  touch-action: manipulation;
  user-select: none;
  -webkit-user-select: none;
  -webkit-touch-callout: none;
  &[data-pressed] {
    transform: scale(var(--mc-press-scale, var(--mc-press-button)));
  }
}

@utility press-card {
  --mc-press-scale: var(--mc-press-card);
}

@utility press-fab {
  --mc-press-scale: var(--mc-press-fab);
}

/* CSS-only transitions (banners, skeleton → content). Reduced motion keeps only the fade. */
@utility transition-ios {
  transition-property: opacity, transform;
  transition-duration: var(--mc-duration-ios);
  transition-timing-function: var(--mc-ease-ios);
  @media (prefers-reduced-motion: reduce) {
    transition-property: opacity;
  }
}
`;
}
