// `pnpm setup:local` — generates git-ignored local-development env files with random secrets.
//
// One file per process, because each process refuses to boot with another process's credentials
// (DECISIONS #7). Existing files are never overwritten unless `--force` is passed. Values are random
// and local-only; nothing here is ever used on staging/production.
//
//   .env.local.compose        passwords used by infra/compose/docker-compose.dev.yml (MongoDB, Redis)
//   .env.local.api-public     api-public    (pnpm dev:app)
//   .env.local.api-admin      api-admin     (pnpm dev:admin)
//   .env.local.worker         worker
//   .env.local.migrate        migrate
//   apps/app/.env.local       musalli PWA build-time VITE_PUBLIC_* values
//   apps/admin/.env.local     admin PWA build-time VITE_PUBLIC_* values
//   infra/compose/.local/redis-users.acl   Redis ACL users generated from the passwords above
import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const force = process.argv.includes('--force');

const secret = (bytes = 24) => randomBytes(bytes).toString('base64url');
const key32 = () => randomBytes(32).toString('base64');

/** Reads KEY=value lines from an existing env file (so regenerating dependants keeps the same passwords). */
function readEnvFile(path) {
  if (!existsSync(path)) return {};
  return Object.fromEntries(
    readFileSync(path, 'utf8')
      .split(/\r?\n/)
      .map((line) => /^([A-Z0-9_]+)=(.*)$/.exec(line))
      .filter(Boolean)
      .map((match) => [match[1], match[2]]),
  );
}

function writeEnvFile(relativePath, header, values) {
  const path = join(root, relativePath);
  if (existsSync(path) && !force) {
    process.stdout.write(`  kept     ${relativePath} (exists; use --force to regenerate)\n`);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  const body = Object.entries(values)
    .map(([name, value]) => `${name}=${value}`)
    .join('\n');
  writeFileSync(
    path,
    `# ${header}\n# Generated by \`pnpm setup:local\` — local development only. Never commit.\n${body}\n`,
    {
      mode: 0o600,
    },
  );
  process.stdout.write(`  wrote    ${relativePath}\n`);
}

// --- Passwords shared by compose and the process env files (reuse existing ones) -------------------
const composePath = join(root, '.env.local.compose');
const existing = force ? {} : readEnvFile(composePath);
const compose = {
  MONGO_ROOT_PASSWORD: existing.MONGO_ROOT_PASSWORD ?? secret(),
  MC_PUBLIC_PASSWORD: existing.MC_PUBLIC_PASSWORD ?? secret(),
  MC_ADMIN_PASSWORD: existing.MC_ADMIN_PASSWORD ?? secret(),
  MC_SYSTEM_PASSWORD: existing.MC_SYSTEM_PASSWORD ?? secret(),
  MC_MIGRATOR_PASSWORD: existing.MC_MIGRATOR_PASSWORD ?? secret(),
  REDIS_RL_PUBLIC_PASSWORD: existing.REDIS_RL_PUBLIC_PASSWORD ?? secret(),
  REDIS_ADMIN_PASSWORD: existing.REDIS_ADMIN_PASSWORD ?? secret(),
  REDIS_WORKER_PASSWORD: existing.REDIS_WORKER_PASSWORD ?? secret(),
};

// --- Dev VAPID key pair (P-256, base64url raw keys) -------------------------------------------------
const { publicKey, privateKey } = generateKeyPairSync('ec', { namedCurve: 'prime256v1' });
const jwkPublic = publicKey.export({ format: 'jwk' });
const jwkPrivate = privateKey.export({ format: 'jwk' });
const vapidPublic = Buffer.concat([
  Buffer.from([4]),
  Buffer.from(jwkPublic.x, 'base64url'),
  Buffer.from(jwkPublic.y, 'base64url'),
]).toString('base64url');
const existingWorker = force ? {} : readEnvFile(join(root, '.env.local.worker'));
const vapid = {
  publicKey: existingWorker.VAPID_PUBLIC_KEY ?? vapidPublic,
  privateKey: existingWorker.VAPID_PRIVATE_KEY ?? jwkPrivate.d,
};

const mongo = (user, password) =>
  `mongodb://${user}:${password}@localhost:27017/?replicaSet=rs0&directConnection=true&authSource=admin`;
const redis = (user, password) => `redis://${user}:${password}@localhost:6379`;

const common = {
  NODE_ENV: 'development',
  APP_ENV: 'local',
  LOG_LEVEL: 'debug',
  MONGODB_DB_NAME: 'masjid_connect_dev',
  APP_ORIGIN: 'http://localhost:5173',
  ADMIN_ORIGIN: 'http://localhost:5174',
  MEDIA_ORIGIN: 'http://localhost:8790',
  TRUSTED_PROXY_MODE: 'none',
};
const encryption = { FIELD_ENCRYPTION_KEY: key32(), FIELD_ENCRYPTION_KEY_ID: 'local1' };

process.stdout.write('Local env files:\n');
writeEnvFile('.env.local.compose', 'docker compose (MongoDB + Redis) passwords', compose);
writeEnvFile('.env.local.api-public', 'api-public', {
  ...common,
  MONGODB_URI_PUBLIC: mongo('mc_public', compose.MC_PUBLIC_PASSWORD),
  REDIS_URL_PUBLIC: redis('rl_public', compose.REDIS_RL_PUBLIC_PASSWORD),
  PORT: '8787',
});
writeEnvFile('.env.local.api-admin', 'api-admin', {
  ...common,
  ...encryption,
  MONGODB_URI_ADMIN: mongo('mc_admin', compose.MC_ADMIN_PASSWORD),
  REDIS_URL_ADMIN: redis('admin', compose.REDIS_ADMIN_PASSWORD),
  SESSION_PEPPER: key32(),
  RP_ID: 'localhost',
  VAPID_PUBLIC_KEY: vapid.publicKey,
  PAYMENT_HOLD_MINUTES: '2',
  PORT: '8788',
});
writeEnvFile('.env.local.worker', 'worker', {
  ...common,
  ...encryption,
  MONGODB_URI_SYSTEM: mongo('mc_system', compose.MC_SYSTEM_PASSWORD),
  REDIS_URL_WORKER: redis('worker', compose.REDIS_WORKER_PASSWORD),
  VAPID_PUBLIC_KEY: vapid.publicKey,
  VAPID_PRIVATE_KEY: vapid.privateKey,
  VAPID_SUBJECT: 'mailto:dev@localhost.invalid',
  PAYMENT_HOLD_MINUTES: '2',
});
writeEnvFile('.env.local.migrate', 'migrate', {
  NODE_ENV: 'development',
  APP_ENV: 'local',
  LOG_LEVEL: 'debug',
  MONGODB_DB_NAME: 'masjid_connect_dev',
  MONGODB_URI_MIGRATOR: mongo('mc_migrator', compose.MC_MIGRATOR_PASSWORD),
});

const client = {
  VITE_PUBLIC_VAPID_PUBLIC_KEY: vapid.publicKey,
  VITE_PUBLIC_APP_ORIGIN: 'http://localhost:5173',
  VITE_PUBLIC_MEDIA_ORIGIN: 'http://localhost:8790',
};
writeEnvFile('apps/app/.env.local', 'musalli PWA (public values — they ship in the bundle)', {
  VITE_PUBLIC_API_BASE: '/api/v1',
  ...client,
  // Cloudflare's documented always-pass test site key (not a secret): https://developers.cloudflare.com/turnstile/troubleshooting/testing/
  VITE_PUBLIC_TURNSTILE_SITE_KEY: '1x00000000000000000000AA',
});
writeEnvFile('apps/admin/.env.local', 'admin PWA (public values — they ship in the bundle)', {
  VITE_PUBLIC_API_BASE: '/api/admin',
  ...client,
});

// --- Redis ACL file (04 §12.2): default user off, one user per process, dangerous commands disabled ----
const aclPath = join(root, 'infra/compose/.local/redis-users.acl');
if (!existsSync(aclPath) || force) {
  mkdirSync(dirname(aclPath), { recursive: true });
  // -@dangerous/-@admin block FLUSHALL, CONFIG, KEYS, DEBUG, … (04 §12.2); INFO is re-allowed because
  // ioredis' ready check and BullMQ's version check need it. Verified against Redis in T0.12.
  const safe = '+@all -@dangerous -@admin +info';
  writeFileSync(
    aclPath,
    [
      'user default off',
      `user rl_public on >${compose.REDIS_RL_PUBLIC_PASSWORD} ~rl:pub:* ${safe}`,
      `user admin on >${compose.REDIS_ADMIN_PASSWORD} ~rl:adm:* ~chal:* ~bull:* ${safe}`,
      `user worker on >${compose.REDIS_WORKER_PASSWORD} ~bull:* ~push:* ~alert:* ${safe}`,
      '',
    ].join('\n'),
    { mode: 0o600 },
  );
  process.stdout.write('  wrote    infra/compose/.local/redis-users.acl\n');
} else {
  process.stdout.write('  kept     infra/compose/.local/redis-users.acl\n');
}

process.stdout.write('\nDone. Start MongoDB + Redis with `pnpm db:start` (needs Docker), then `pnpm dev`.\n');
